server:
  port: 8080

spring:
  profiles:
    active: dev
  jpa:
    open-in-vew: false
  hibernate:
    format_sql: true
  properties:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl